- hosts: cape_clients
  name: Install Choco/Boxstarter and search for packages
  tasks:
  - name: Ensure C:/temp directory exists
    win_file:
      path: C:/temp
      state: directory
  - name: Install Boxstarter
    win_chocolatey:
      name: boxstarter
      state: present
  - loop: &id001
    - name: firefox
      version: 78.0.1
    - name: adobereader
      version: 2018.011.20058
    name: Execute choco search for each software and version
    register: search_results
    win_shell: choco search "{{ item.name }}" --all-versions > C:/temp/{{ item.name
      }}_choco_search_results.txt
  - fetch:
      dest: ansible/search_results/
      flat: 'yes'
      src: C:/temp/{{ item.name }}_choco_search_results.txt
    loop: *id001
    name: Fetch the files from remote machine
